#include "NumberDie.h"
#include "random"


/*This is the implementation file for the NumberDie derrived class*/

/*The roll function simulates a die rolling. A random number is generated
 *in the range of the array and then the selected face is returned*/
std::string NumberDie::roll() {
	//random device engine
	std::random_device rd;

	//range of numbers to be generated by engine, between 1 and number of sides.
	std::uniform_int_distribution<int> dist(1, sides);

	//returns the random number created by random engine within the range of the distribution list, as a string.
	return std::to_string(dist(rd));
}


/*The get faces method uses a for loop to print out the possible numbers on a dies face, up to a D20*/
std::string NumberDie::getFaces() {
	std::string faces;

	for (int i = 1; i < 21; i++) {
		faces = faces + " " + std::to_string(i);
	}

	return faces;
}
